// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Seguradora.api.Migrations
{
    [DbContext(typeof(SeguradoraDbContext))]
    [Migration("20260923184220_AdicionarApolicesESinistros")]
    partial class AdicionarApolicesESinistros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("Apolice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeguradoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorSegurado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("VigenciaEmMeses")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoId");

                    b.ToTable("Apolices", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("Apolice");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Cobertura", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApoliceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LimiteIndenizacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApoliceId");

                    b.ToTable("Coberturas", (string)null);
                });

            modelBuilder.Entity("Segurado", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("Cpf");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Segurados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "SEG00001",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1988, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Documento = "52998224725",
                            Nome = "Maria Silva"
                        },
                        new
                        {
                            Id = "SEG00002",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2004, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Documento = "11144477735",
                            Nome = "João Souza"
                        });
                });

            modelBuilder.Entity("Sinistro", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApoliceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoNegativa")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoOcorrencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPleiteado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApoliceId");

                    b.ToTable("Sinistros", (string)null);
                });

            modelBuilder.Entity("ApoliceAutomovel", b =>
                {
                    b.HasBaseType("Apolice");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Automovel");
                });

            modelBuilder.Entity("ApoliceResidencial", b =>
                {
                    b.HasBaseType("Apolice");

                    b.Property<decimal>("AreaConstruida")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PossuiAlarme")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Residencial");
                });

            modelBuilder.Entity("ApoliceVida", b =>
                {
                    b.HasBaseType("Apolice");

                    b.Property<bool>("Fumante")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Vida");
                });

            modelBuilder.Entity("Apolice", b =>
                {
                    b.HasOne("Segurado", "Segurado")
                        .WithMany()
                        .HasForeignKey("SeguradoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Segurado");
                });

            modelBuilder.Entity("Cobertura", b =>
                {
                    b.HasOne("Apolice", null)
                        .WithMany("Coberturas")
                        .HasForeignKey("ApoliceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sinistro", b =>
                {
                    b.HasOne("Apolice", "Apolice")
                        .WithMany()
                        .HasForeignKey("ApoliceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apolice");
                });

            modelBuilder.Entity("Apolice", b =>
                {
                    b.Navigation("Coberturas");
                });
#pragma warning restore 612, 618
        }
    }
}
