// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Seguradora.api.Migrations
{
    [DbContext(typeof(SeguradoraDbContext))]
    partial class SeguradoraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("Segurado", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("Cpf");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Segurados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "SEG00001",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1988, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Documento = "52998224725",
                            Nome = "Maria Silva"
                        },
                        new
                        {
                            Id = "SEG00002",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2004, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Documento = "11144477735",
                            Nome = "João Souza"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
